version: '3'
services:
  user-service:
    build:
      context: ./
      dockerfile: ./user-service/Dockerfile.dev
    ports:
      - 3000:3000
      - 9228:9229
    volumes:
      - /usr/app/node_modules
      - ./user-service:/usr/app
    environment:
      - NODE_ENV=development
      - EXPRESS_PORT=3000
      - JWT_SECRET=trustnoone
    depends_on:
      - mongodb-server
    command: ["npm", "run", "debug"]
  post-service:
    build:
      context: ./
      dockerfile: ./post-service/Dockerfile.dev
    ports:
      - 3001:3000
      - 9229:9229
    volumes:
      - /usr/app/node_modules
      - ./post-service:/usr/app
    environment:
      - NODE_ENV=development
      - EXPRESS_PORT=3000
      - JWT_SECRET=trustnoone
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/serene-smoke-316705-dbe6d71303f7.json
    depends_on:
      - mongodb-server
    command: ["npm", "run", "debug"]
  redis-server:
    image: redis
  mongodb-server:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - ./mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
      ME_CONFIG_MONGODB_SERVER: mongodb-server