version: '3'
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./user-service:/usr/app